[phases.setup]
# AQUI ESTAVA O ERRO: Faltava o composer na lista
nixPkgs = ["php81", "php81Extensions.pdo", "php81Extensions.pdo_pgsql", "php81Packages.composer"]

[phases.build]
cmds = ["composer install --ignore-platform-reqs"]

[start]
cmd = "php -S 0.0.0.0:$PORT"